[package]
name = "rink"
version = "0.2.1"
authors = ["Tiffany Bennett <tiffany@stormbit.net>"]
description = "Unit conversion tool and library, similar to frink"
homepage = "https://github.com/tiffany352/rink-rs"
repository = "https://github.com/tiffany352/rink-rs"
readme = "README.md"
license = "MPL-2.0"
keywords = ["unit", "math", "conversion", "cli", "tool"]

[features]
default = ["rustyline", "chrono-humanize"]
ircbot = ["irc", "glob"]
web = ["hyper", "url", "sandbox"]
sandbox = ["libc", "ipc-channel"]

[dependencies]
rust-gmp = "0.3.2"
chrono = "0.2.25"
chrono-humanize = { version = "0.0.6", optional = true }
rustyline = { version = "0.2.3", optional = true }
irc = { version = "0.11.3", optional = true }
glob = { version = "0.2.11", optional = true }
hyper = { version = "0.9.10", optional = true }
url = { version = "1.2.0", optional = true }
libc = { version = "0.2.14", optional = true }
ipc-channel = { version = "0.5.1", optional = true }

[[bin]]
name = "rink"
doc = false

[[bin]]
name = "rink-debug-tokens"
doc = false

[[bin]]
name = "rink-irc"
doc = false

[[bin]]
name = "rink-web"
doc = false
