[package]
name = "rink"
version = "0.2.1"
authors = ["Tiffany Bennett <tiffany@stormbit.net>"]
description = "Unit conversion tool and library, similar to frink"
homepage = "https://github.com/tiffany352/rink-rs"
repository = "https://github.com/tiffany352/rink-rs"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["unit", "math", "conversion", "cli", "tool"]

[features]
default = ["rustyline"]
ircbot = ["irc", "glob"]

[dependencies]
rust-gmp = "0.3.2"
chrono = "0.2.25"
rustyline = { version = "0.2.3", optional = true }
irc = { version = "0.11.3", optional = true }
glob = { version = "0.2.11", optional = true }

[[bin]]
name = "rink"
doc = false

[[bin]]
name = "rink-debug-tokens"
doc = false

[[bin]]
name = "rink-irc"
doc = false
