[package]
name = "rink"
version = "0.1.0"
authors = ["Tiffany Bennett <tiffany@stormbit.net>"]
description = "Unit conversion tool and library, similar to frink"
homepage = "https://github.com/tiffany352/rink-rs"
repository = "https://github.com/tiffany352/rink-rs"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["unit", "math", "conversion", "cli", "tool"]

[features]
default = ["rustyline"]

[dependencies]
rustyline = { version = "0.2.3", optional = true }
