[package]
name = "rink-web"
version = "0.3.2"
authors = ["Tiffany Bennett <tiffany@stormbit.net>"]
description = "Web interface to Rink"
homepage = "https://github.com/tiffany352/rink-rs"
repository = "https://github.com/tiffany352/rink-rs"
readme = "README.md"
license = "MPL-2.0"

[features]
watch = ["handlebars-iron/watch"]
lmdb = ["rink/lmdb"]

[dependencies.rink]
path = "../"
features = ["nightly"]

[dependencies]
iron = "0.4.0"
router = "0.4.0"
params = "0.4.0"
handlebars = "0.20.0"
handlebars-iron = "0.18.0"
staticfile = "0.3.0"
mount = "0.2.1"
ipc-channel = "0.5.1"
libc = "0.2.14"
chrono = { version = "*", features = ["serde"] }
rustc-serialize = "*"
serde_json = "0.8"
serde_derive = "0.8"
serde = "0.8"
limiter = "0.2"
logger = "0.1.0"
url = "1.2.0"
toml = { version = "0.2", features = ["serde"] }
