[package]
name = "rink-web"
version = "0.3.2"
authors = ["Tiffany Bennett <tiffany@stormbit.net>"]
description = "Web interface to Rink"
homepage = "https://github.com/tiffany352/rink-rs"
repository = "https://github.com/tiffany352/rink-rs"
readme = "README.md"
license = "MPL-2.0"

[dependencies.rink]
path = "../"
features = ["hyper", "sandbox"]

[dependencies]
iron = "0.4.0"
router = "0.4.0"
params = "0.4.0"
